CREATE TABLE IF NOT EXISTS analyzed_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(39) NOT NULL,
  github_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) NULL,
  avatar_url VARCHAR(512) NOT NULL,
  bio TEXT NULL,
  location VARCHAR(255) NULL,
  company VARCHAR(255) NULL,
  blog VARCHAR(512) NULL,
  github_profile_url VARCHAR(512) NOT NULL,
  public_repos INT UNSIGNED NOT NULL DEFAULT 0,
  followers INT UNSIGNED NOT NULL DEFAULT 0,
  following INT UNSIGNED NOT NULL DEFAULT 0,
  account_created_at DATETIME NOT NULL,
  account_age_years DECIMAL(5,2) NOT NULL DEFAULT 0,
  total_stars INT UNSIGNED NOT NULL DEFAULT 0,
  total_forks INT UNSIGNED NOT NULL DEFAULT 0,
  most_starred_repo_name VARCHAR(255) NULL,
  most_starred_repo_stars INT UNSIGNED NOT NULL DEFAULT 0,
  top_language VARCHAR(100) NULL,
  avg_stars_per_repo DECIMAL(10,2) NOT NULL DEFAULT 0,
  score INT UNSIGNED NOT NULL DEFAULT 0,
  developer_level VARCHAR(32) NOT NULL,
  language_summary_json JSON NOT NULL,
  activity_data_json JSON NOT NULL,
  activity_summary_json JSON NOT NULL,
  insights_json JSON NOT NULL,
  raw_profile_json JSON NOT NULL,
  raw_repos_json JSON NOT NULL,
  raw_events_json JSON NOT NULL,
  analyzed_at DATETIME NOT NULL,
  refreshed_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_analyzed_profiles_username (username),
  UNIQUE KEY uk_analyzed_profiles_github_id (github_id),
  KEY idx_analyzed_profiles_score (score),
  KEY idx_analyzed_profiles_level (developer_level),
  KEY idx_analyzed_profiles_language (top_language),
  KEY idx_analyzed_profiles_followers (followers),
  KEY idx_analyzed_profiles_analyzed_at (analyzed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS analyzed_profile_repositories (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  profile_id BIGINT UNSIGNED NOT NULL,
  github_repo_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  html_url VARCHAR(512) NOT NULL,
  description TEXT NULL,
  language VARCHAR(100) NULL,
  stars INT UNSIGNED NOT NULL DEFAULT 0,
  forks INT UNSIGNED NOT NULL DEFAULT 0,
  watchers INT UNSIGNED NOT NULL DEFAULT 0,
  size INT UNSIGNED NOT NULL DEFAULT 0,
  pushed_at DATETIME NULL,
  updated_at_github DATETIME NULL,
  is_fork TINYINT(1) NOT NULL DEFAULT 0,
  is_archived TINYINT(1) NOT NULL DEFAULT 0,
  raw_repo_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_profile_repo (profile_id, github_repo_id),
  KEY idx_repo_profile_id (profile_id),
  KEY idx_repo_stars (stars),
  KEY idx_repo_language (language),
  CONSTRAINT fk_repo_profile FOREIGN KEY (profile_id) REFERENCES analyzed_profiles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS analyzed_profile_languages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  profile_id BIGINT UNSIGNED NOT NULL,
  language_name VARCHAR(100) NOT NULL,
  repo_count INT UNSIGNED NOT NULL DEFAULT 0,
  stars INT UNSIGNED NOT NULL DEFAULT 0,
  percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_profile_language (profile_id, language_name),
  KEY idx_language_profile_id (profile_id),
  CONSTRAINT fk_language_profile FOREIGN KEY (profile_id) REFERENCES analyzed_profiles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;